import pandas as pd
import requests
import smtplib
from email.message import EmailMessage
from datetime import datetime
import os

# --- 1. API Data Extraction ---
# Pulling live market data using a financial API endpoint
API_URL = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=demo"
response = requests.get(API_URL)
raw_data = response.json().get('Time Series (Daily)', {})

# --- 2. Data Processing (pandas) ---
if raw_data:
    df = pd.DataFrame.from_dict(raw_data, orient='index')
    df = df.rename(columns=lambda x: x.split('. ')[1]) # Clean column names
    df = df.astype(float) # Ensure numerical data types
    df.index = pd.to_datetime(df.index)
    df = df.sort_index(ascending=False).head(30) # Isolate 30-day window
    
    # Calculate financial metric
    df['Daily_Return'] = df['close'].pct_change(-1)
else:
    print("API Error: No data retrieved.")
    exit()

# --- 3. Excel Export ---
report_name = f"Market_Report_{datetime.now().strftime('%Y%m%d')}.xlsx"
df.to_excel(report_name, sheet_name="Market_Analysis")
print(f"Report generated: {report_name}")

# --- 4. Email Distribution (smtplib) ---
def distribute_report(file_path):
    # Security: Use environment variables, never hardcode credentials
    sender = os.environ.get("EMAIL_USER") 
    password = os.environ.get("EMAIL_PASS")
    recipient = "target_address@financefirm.com"

    if not sender or not password:
        print("Credentials missing. Setup environment variables.")
        return

    msg = EmailMessage()
    msg['Subject'] = f"Automated Daily Market Report - {datetime.now().strftime('%Y-%m-%d')}"
    msg['From'] = sender
    msg['To'] = recipient
    msg.set_content("Attached is the daily automated market analysis generated by the Python pipeline.")

    # Attach the Excel file
    with open(file_path, 'rb') as f:
        excel_data = f.read()
    msg.add_attachment(
        excel_data, 
        maintype='application', 
        subtype='vnd.openxmlformats-officedocument.spreadsheetml.sheet', 
        filename=file_path
    )

    # Secure SMTP transmission
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, password)
            server.send_message(msg)
        print("Success: Pipeline completed and report distributed.")
    except Exception as e:
        print(f"Transmission Error: {e}")

# Execute Distribution
# distribute_report(report_name)